// export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD"
export const SERVICES_UPLOAD_REQUEST = "SERVICES_UPLOAD_REQUEST"
export const SERVICES_UPLOAD_FAILURE = "SERVICES_UPLOAD_FAILURE"
export const SERVICES_UPLOAD_SUCCESS = "SERVICES_UPLOAD_SUCCESS"
